service: one-liner-pyccho
frameworkVersion: "2"
provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  timeout: 30
  memorySize: 256
  environment:
    SLACK_OAUTH_TOKEN: ${env:SLACK_OAUTH_TOKEN}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
functions:
  pyccho:
    handler: src/pyccho.handler
    events:
      - http:
          path: pyccho
          method: post
          async: true
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
